/*
 * Blocks.cpp
 * RVO2 Library
 *
 * Copyright 2008 University of North Carolina at Chapel Hill
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please send all bug reports to <geom@cs.unc.edu>.
 *
 * The authors may be contacted via:
 *
 * Jur van den Berg, Stephen J. Guy, Jamie Snape, Ming C. Lin, Dinesh Manocha
 * Dept. of Computer Science
 * 201 S. Columbia St.
 * Frederick P. Brooks, Jr. Computer Science Bldg.
 * Chapel Hill, N.C. 27599-3175
 * United States of America
 *
 * <https://gamma.cs.unc.edu/RVO2/>
 */

/*
 * Example file showing a demo with 100 agents split in four groups initially
 * positioned in four corners of the environment. Each agent attempts to move to
 * other side of the environment through a narrow passage generated by four
 * obstacles. There is no roadmap to guide the agents around the obstacles.
 */

#ifndef RVO_OUTPUT_TIME_AND_POSITIONS
#define RVO_OUTPUT_TIME_AND_POSITIONS 1
#endif

#ifndef RVO_SEED_RANDOM_NUMBER_GENERATOR
#define RVO_SEED_RANDOM_NUMBER_GENERATOR 1
#endif

#include <cmath>
#include <cstdlib>

#include <vector>

#if RVO_OUTPUT_TIME_AND_POSITIONS
#include <iostream>
#endif

#if RVO_SEED_RANDOM_NUMBER_GENERATOR
#include <ctime>
#endif

#if _OPENMP
#include <omp.h>
#endif

#include <RVO.h>
#include <Eigen/Dense>
#include <GL/glut.h>
//#define TEST
#ifndef M_PI
const double M_PI = 3.14159265358979323846f;
#endif
const static int WINDOW_WIDTH = 1000;
const static int WINDOW_HEIGHT = 1000;
const static double VIEW_WIDTH = 500;
const static double VIEW_HEIGHT = 500;
/* Store the goals of the agents. */
std::vector<RVO::Vector2> goals;
RVO::RVOSimulator *sim = new RVO::RVOSimulator();
void InitGL(void)
{
	glClearColor(0.9f,0.9f,0.9f,1);
	glEnable(GL_POINT_SMOOTH);
	glPointSize(10.0);
	glMatrixMode(GL_PROJECTION);
}
void Render(void)
{
	glClearColor(0.9f,0.9f,0.9f,1);
	glClear(GL_COLOR_BUFFER_BIT);
	glLoadIdentity();
	glOrtho(0, VIEW_WIDTH, 0, VIEW_HEIGHT, 0, 1);
	glClearColor(0.4, 0.6, 0.7, 1);
	glRectf(180, 180, 210, 210);
	glRectf(180, 290, 210, 320);
	glRectf(290, 180, 320, 210);
	glRectf(290, 290, 320, 320);
	glBegin(GL_POINTS);
	glColor4f(0.2f, 0.6f, 1.0f, 1);
	for (size_t i = 0; i < sim->getNumAgents(); i+=4) {
		glVertex2f(250+sim->getAgentPosition(i).x(),250+sim->getAgentPosition(i).y());
	}
	glColor4f(0.8f, 0.6f, 1.0f, 1);
	for (size_t i = 1; i < sim->getNumAgents(); i+=4) {
		glVertex2f(250+sim->getAgentPosition(i).x(),250+sim->getAgentPosition(i).y());
	}
	glColor4f(0.4f, 0.6f, 0.3f, 1);
	for (size_t i = 2; i < sim->getNumAgents(); i+=4) {
		glVertex2f(250+sim->getAgentPosition(i).x(),250+sim->getAgentPosition(i).y());
	}
	glColor4f(0.8f, 0.3f, 0.6f, 1);
	for (size_t i = 3; i < sim->getNumAgents(); i+=4) {
		glVertex2f(250+sim->getAgentPosition(i).x(),250+sim->getAgentPosition(i).y());
	}
	glEnd();

    glFlush();
	glutSwapBuffers();

}

void setupScenario(RVO::RVOSimulator *sim)
{
#if RVO_SEED_RANDOM_NUMBER_GENERATOR
	std::srand(static_cast<unsigned int>(std::time(NULL)));
#endif

	/* Specify the global time step of the simulation. */
	sim->setTimeStep(0.5f);
	sim->setNewtonParameters(100,1e-2,50,1e0,1e-6);
	/* Specify the default parameters for agents that are subsequently added. */
	sim->setAgentDefaults(15.0f, 100, 10.0, 10.0, 1.5f, 2.0f);

	/*
	 * Add agents, specifying their start position, and store their goals on the
	 * opposite side of the environment.
	 */
	for (size_t i = 0; i < 5; ++i) {
		for (size_t j = 0; j < 5; ++j) {
			sim->addAgent(RVO::Vector2(85.0f + i * 10.0,  85.0f + j * 10.0)+0.005*RVO::Vector2(rand()%1000,rand()%1000));
			goals.push_back(RVO::Vector2(-105.0f, -105.0f));

			sim->addAgent(RVO::Vector2(-85.0f - i * 10.0,  85.0f + j * 10.0)+0.005*RVO::Vector2(rand()%1000,rand()%1000));
			goals.push_back(RVO::Vector2(105.0f, -105.0f));

			sim->addAgent(RVO::Vector2(85.0f + i * 10.0, -85.0f - j * 10.0)+0.005*RVO::Vector2(rand()%1000,rand()%1000));
			goals.push_back(RVO::Vector2(-105.0f, 105.0f));

			sim->addAgent(RVO::Vector2(-85.0f - i * 10.0, -85.0f - j * 10.0)+0.005*RVO::Vector2(rand()%1000,rand()%1000));
			goals.push_back(RVO::Vector2(105.0f, 105.0f));
		}
	}

	/*
	 * Add (polygonal) obstacles, specifying their vertices in counterclockwise
	 * order.
	 */
	std::vector<RVO::Vector2> obstacle1, obstacle2, obstacle3, obstacle4;

	obstacle1.push_back(RVO::Vector2(-40.0, 70.0));
	obstacle1.push_back(RVO::Vector2(-70.0, 70.0));
	obstacle1.push_back(RVO::Vector2(-70.0, 40.0));
	obstacle1.push_back(RVO::Vector2(-40.0, 40.0));

	obstacle2.push_back(RVO::Vector2(40.0, 70.0));
	obstacle2.push_back(RVO::Vector2(40.0, 40.0));
	obstacle2.push_back(RVO::Vector2(70.0, 40.0));
	obstacle2.push_back(RVO::Vector2(70.0, 70.0));

	obstacle3.push_back(RVO::Vector2(40.0, -70.0));
	obstacle3.push_back(RVO::Vector2(70.0, -70.0));
	obstacle3.push_back(RVO::Vector2(70.0, -40.0));
	obstacle3.push_back(RVO::Vector2(40.0, -40.0));

	obstacle4.push_back(RVO::Vector2(-40.0, -70.0));
	obstacle4.push_back(RVO::Vector2(-40.0, -40.0));
	obstacle4.push_back(RVO::Vector2(-70.0, -40.0));
	obstacle4.push_back(RVO::Vector2(-70.0, -70.0));

	sim->addObstacle(obstacle1);
	sim->addObstacle(obstacle2);
	sim->addObstacle(obstacle3);
	sim->addObstacle(obstacle4);

	/* Process the obstacles so that they are accounted for in the simulation. */
	sim->processObstacles();
}

#if RVO_OUTPUT_TIME_AND_POSITIONS
void updateVisualization(RVO::RVOSimulator *sim)
{
	/* Output the current global time. */
	std::cout << sim->getGlobalTime();

	/* Output the current position of all the agents. */
	for (size_t i = 0; i < sim->getNumAgents(); ++i) {
		std::cout << " " << sim->getAgentPosition(i);
	}

	std::cout << std::endl;
}
#endif

void setPreferredVelocities(RVO::RVOSimulator *sim)
{
	/*
	 * Set the preferred velocity to be a vector of unit magnitude (speed) in the
	 * direction of the goal.
	 */
#ifdef _OPENMP
#pragma omp parallel for
#endif
	for (int i = 0; i < static_cast<int>(sim->getNumAgents()); ++i) {
		RVO::Vector2 goalVector = goals[i] - sim->getAgentPosition(i);

		if (RVO::absSq(goalVector) > 1.0f) {
			goalVector = RVO::normalize(goalVector);
		}

		sim->setAgentPrefVelocity(i, goalVector);

		/*
		 * Perturb a little to avoid deadlocks due to perfect symmetry.
		 */
		double angle = std::rand() * 2.0f * M_PI / RAND_MAX;
		double dist = std::rand() * 0.0001f / RAND_MAX;

		sim->setAgentPrefVelocity(i, sim->getAgentPrefVelocity(i) +
		                          dist * RVO::Vector2(std::cos(angle), std::sin(angle)));
	}
}

bool reachedGoal(RVO::RVOSimulator *sim)
{
	/* Check if all agents have reached their goals. */
	for (size_t i = 0; i < sim->getNumAgents(); ++i) {
		if (RVO::absSq(sim->getAgentPosition(i) - goals[i]) > 20.0 * 20.0) {
			return false;
		}
	}

	return true;
}
void Update(void)
{
    #if RVO_OUTPUT_TIME_AND_POSITIONS
		//updateVisualization(sim);
	#endif
		setPreferredVelocities(sim);
	#ifdef TEST
		sim->checkEnergyFD();
	#else
		sim->doStep();
	#endif	
		glutPostRedisplay();
}
int main(int argc, char **argv)
{
	/* Create a new simulator instance. */
	/* Set up the scenario. */
	setupScenario(sim);

	/* Perform (and manipulate) the simulation. */
	/*do {

	}
	while (!reachedGoal(sim));*/
    glutInitWindowSize(WINDOW_WIDTH,WINDOW_HEIGHT);
	glutInit(&argc, argv);
	glutCreateWindow("SPH");
	glutDisplayFunc(Render);
	glutIdleFunc(Update);
    InitGL();
	glutMainLoop();

	delete sim;

	return 0;
}
